<?php

/**
 * Implementation of hook_help().
 */
function system_service_help($section) {
  switch ($section) {
    case 'admin/help#services_node':
      return t('<p>Provides node methods to services applications. Requires services.module.</p>');
    case 'admin/modules#description':
      return t('Provides node methods to services applications. Requires services.module.');
  }
}

/**
 * Implementation of hook_service()
 */
function system_service_service() {
  return array(
    
    // system.connect
    array(
      '#method'   => 'system.connect',
      '#callback' => 'system_service_connect',
      '#auth'     => false,
      '#return'   => 'struct',
      '#help'     => t('Returns an object containing a sessid and user.')),
      
    // system.mail
    array(
      '#method'   => 'system.mail',
      '#callback' => 'system_service_mail',
      '#args'     => array(
        array(
          '#name'         => 'mailkey',
          '#type'         => 'string',
          '#description'  => t('A key to identify the mail sent, for altering.'),
        ),
        array(
          '#name'         => 'to',
          '#type'         => 'string',
          '#description'  => t('The mail address or addresses where the message will be send to.'),
        ),
        array(
          '#name'         => 'subject',
          '#type'         => 'string',
          '#description'  => t('Subject of the e-mail to be sent. This must not contain any newline characters, or the mail may not be sent properly.'),
        ),
        array(
          '#name'         => 'body',
          '#type'         => 'string',
          '#description'  => t('Message to be sent. Drupal will format the correct line endings for you.'),
        ),
        array(
          '#name'         => 'from',
          '#type'         => 'string',
          '#optional'     => true,
          '#description'  => t('Sets From, Reply-To, Return-Path and Error-To to this value, if given.'),
        ),
        array(
          '#name'         => 'headers',
          '#type'         => 'array',
          '#optional'     => true,
          '#description'  => t('Associative array containing the headers to add. This is typically used to add extra headers (From, Cc, and Bcc).'),
        ),
      ),
      '#return'   => 'struct',
      '#help'     => t('Send an e-mail message, using Drupal variables and default settings.')),
  );
}

/**
 * Returns a specified node.
 */
function system_service_connect() {
  global $user;
  
  $return = new stdClass();
  $return->sessid = session_id();
  $return->user = $user;
  
  return $return;
}

function system_service_mail($mailkey, $to, $subject, $body, $from = NULL, $headers = array()) {
  $status = drupal_mail($mailkey, $to, $subject, $body, $from, $headers);
  if (!$status) {
    return services_error(t('There was a problem sending your email.'));
  }
  
  return $status;
}